-- MySQL Script generated by MySQL Workbench
-- Wed Sep 13 11:23:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newsdb` DEFAULT CHARACTER SET utf8 ;
USE `newsdb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsdb`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(200) NOT NULL,
  `user_avatar` VARCHAR(100) NULL DEFAULT 'null',
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `modified_at` DATETIME NULL DEFAULT NULL,
  `biography` VARCHAR(100) NULL,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsdb`.`themes` (
  `themes_id` INT NOT NULL,
  `celebrities` VARCHAR(45) NOT NULL,
  `premiers` VARCHAR(45) NOT NULL,
  `oscar_2024` VARCHAR(45) NOT NULL,
  `criticas` VARCHAR(45) NOT NULL,
  `ranking` VARCHAR(45) NOT NULL,
  `festivals` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`themes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsdb`.`news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `new_title` VARCHAR(100) NOT NULL,
  `new_pic` VARCHAR(100) NULL,
  `new_entrance` VARCHAR(100) NULL,
  `new_text` VARCHAR(1000) NOT NULL,
  `new_theme` VARCHAR(45) NOT NULL,
  `new_video` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `modified_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `users_user_id` INT UNSIGNED NOT NULL,
  `themes_themes_id` INT NOT NULL,
  UNIQUE INDEX `id_new_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `users_user_id`, `themes_themes_id`),
  INDEX `fk_news_users_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_news_themes1_idx` (`themes_themes_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `newsdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_themes1`
    FOREIGN KEY (`themes_themes_id`)
    REFERENCES `newsdb`.`themes` (`themes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
